# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
#    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:mysql://localhost:3306/update_db
    username: root
    password:


# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
#    jdbc: OFF
#      sqltiming: DEBUG
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO